name: cd

on:
  push:
    branches: [ main ]

jobs:
  docker-push:
    uses: grrrrrrh/pipeline-kit/.github/workflows/docker-build-push.yml@main
    with:
      image: ghcr.io/${{ github.repository }}
      push: true
      tags: |
        ghcr.io/${{ github.repository }}:main
        ghcr.io/${{ github.repository }}:sha-${{ github.sha }}
