name: ci

on:
  pull_request:
    branches: [ main ]

jobs:
  docker-build:
    uses: grrrrrrh/pipeline-kit/.github/workflows/docker-build-push.yml@main
    with:
      image: ghcr.io/${{ github.repository }}
      push: false
      tags: ghcr.io/${{ github.repository }}:pr-${{ github.event.number }}-${{ github.sha }}
